### PR TITLE
LDP: add, update, etag handling, and sparql-update patch

### PR DESCRIPTION
**Pull request by sylvainlb**

### CODE REVIEW

**Comment by sylvainlb** [comment]
We should probably handle different patch formats, but that should be based on the server's Accept header. I'm not sure where to do this. We could perform a HEAD request before every PATCH, but that wouldn't be very efficient

**Comment by bergos** [comment]
Thanks for the patch! A fixed mime type is better than nothing. It should be possibe to do a PATCH and resend the content in a different format on a 415 or some other 4xx response.

The ETag code works only for cases where the graph object is reused. But that example would cause an error:
```
store.graph('http://example.org/graph', function (graphA) {
  var graphB = rdf.parseTurtle(aTurtleString, function (graphB) {
    store.merge('http://example.org/graph', graphB);
  });
});
```
Maybe a IRI to ETag map could be used. But can we always use the latest version? What if an application handles to different version of the graph?

**Comment by sylvainlb** [comment]
Thanks for your comments. Your solution for the mime type is probably a good start. In fact it looks like the question of mime type of PATCH request is still not completely closed at the w3c.

As for the Etag question, you're absolutely right. I assumed that it was the caller's responsibility to set the etag on the graph. Indeed your point about having 2 different versions is relevant, as one can get 2 different parts of the graph at 2 different times. Then the graph may have change between the 2 get requests, so an update on the first part should be rejected.

My understanding of the etag part of the specification is that it's the client responsibility to make sure it's not patching a resource without checking it's safe. If that's the case, then your example code is incorrect and should cause an error.

**Comment by bergos** [comment]
@sylvainlb
The latest commit should cover all your requirements. I changed the code a little bit and also the interfaces, so they match better with the generic concept of RDF-Interfaces + RDF-Ext.

There is now a options parameter in the .graph, .add and .merge method. I use that parameter already in the Universal Access Control code in LDApp stack for additional stuff.

To use the etag property in the graph you just have to add the options property useEtag:true. It's also possible to set the ETag directly using the etag:value options property.

RDF-Ext usually works only with known named graph IRIs. The HTTP method POST doesn't fit very well into that concept. To cover that case, I added a method options to the .add method.

I don't have a 100% compatible LDP server on my test environment. So I couldn't test my changes. It would be great if you could add a quick start section to your LDP-Todo-List readme.

**Comment by sylvainlb** [comment]
Thanks, nicely done!
I didn't understand hy doesn't POST fit very well with the RDF-Ext concept. Could you elaborate? The standard allows both POST and PUT and even other methods, so it's mostly up to the server, and it seems there's no consensus so far, so flexibility is indeed probably the right way to go.

I'm currently working with Henry Story to have a simple distributed version of RwwPlay. Give me a few more days and I'll let you know where you can get it.

**Comment by bergos** [comment]
There is a unique aspect in the POST method: The response is required to know the final IRI.

RDF-Ext is based on RDF-Interfaces and the RDF Model in mind. From the model perspective the POST method combines an IRI factory + an insert statement. But from my point of view using the options object is a good solution.

Btw. Shouldn't we add another option to copy the value of the Location header field of a POST response to a .iri property like the .etag property in the .graph method?

**Comment by sylvainlb** [comment]
I see your point. I've actually been thinking too that we need to store the container uri somewhere, but I'm still not sure where. I need more thinking on that.

By the way, it seems the source code of https://github.com/webr3/rdf-interfaces is not up to date with the one we get from npm install. Do you know where the latest release is?

**Comment by bergos** [comment]
Where do you get the container URI from? The Link HTTP header field? This header field describes an additional graph. So I would propose to store that graph as .link property of the main graph object.

[Here](https://github.com/bergos/rdf-interfaces) is the source of the rdf-interfaces npm package. I created an issue to update the URLs in packages.json...

**Comment by sylvainlb** [comment]
Thanks for the link.
I'm still not sure about the uri issue. I'm working on LDP usage and I guess that'll help defining how that uri should be handled.

**Comment by sylvainlb** [comment]
Hello, you might be interested in the new prototype I worked on, especially in the store class I designed: https://github.com/Open-Initiative/LDP-Todo-List/blob/master/LdpStore.js

My goal was to define a generic way to get javascript objects from LDP resources. It's not clean, and the data it uses is not clean either, but I was trying to get the idea. I used the json serializer to get objects from the graph, but I'm not sure if it was the best option.

Anyway I still need to solve a few issues:
1. the blank nodes aren't included in the object, so I need to request the graph for each child node
2. the serializer don't create arrays when there is only 1 value in them, so it's a pain for the developer who has to check if things are array or objects
3. I'd like to set a cache mechanism that could get the resource on the server only once

The other thing I'm wondering is what kind of integration should be provided with rdf-ext.

Please let me know if you have any idea about all these questions.
Thanks!

**Comment by bergos** [comment]
Sorry for the delayed response. I will add a IRI property, very similar to the eTag property, in the next days.

1.
2.
You should always preprocess JSON-LD data if you want to use it like a usual JSON object. See [JSOND-LD API Spec #Features](http://www.w3.org/TR/json-ld-api/#features). And very useful to try the different algorithm with your own data: [JSON-LD Playground ](http://json-ld.org/playground/)

3.
Caching will be integrated into RDF-Ext using a wrapper store. But it’s not as easy as it looks, because a offline- / sync-store is also in the todo list and is very similar. For your own store code I would suggest to use a object to create a simple graph IRI to graph map in your .fetchAll method.

I’m not sure what you mean with integration provided with rdf-ext. Can you please explain it in more detail?

**Comment by sylvainlb** [comment]
"You should always preprocess JSON-LD data" => do you mean parse & serialize it? That's what I do, but I lose some structure in the process: the link to the blank nodes, and the array organization. I guess my library should simplify that for the client.

That was actually my point about the integration. Some features should be added directly to rdf-ext, like the caching, some maybe need to be in another layer. So I'm wondering about the status of what I'm doing. Like should it be another store for rdf-ext or an interface?

In any case let me know if I can help you with the development of rdf-ext. I'll definitely do the missing calls like delete as soon as I find the time. And I'll test it with several LDP servers.

**Comment by bergos** [comment]
With preprocess I mean calls to jsonld.compact, jsonld.expand, etc. with your own JSON-LD context. The RDF-Ext serializer creates JSON-LD objects like the jsonld.flatten method would do, because that’s the easiest way. [RDF-JSONify](https://github.com/bergos/rdf-jsonify) could be interesting for you.

RDF-Ext is an extension to RDF-Interfaces, so it contains mainly low level components. Everything that implements a parser, serializer or store interface and is reusable for other people is very welcome to become part of RDF-Ext!

Also RDF-Ext should be easy to use. Thats why some utils are required. RDF-JSONify will be the first one, which I want to merge into the RDF-Ext package. Second is a [Pointed Graph](https://github.com/zazukoians/rdf-ext/issues/23) like interface. Your code uses ideas of both concepts. Maybe you want to join the [rdfjs discussion](https://lists.w3.org/Archives/Public/public-rdfjs/2015Mar/0004.html) to talk about further steps.

**Comment by sylvainlb** [comment]
Thanks a lot, that's precisely what I was looking for. jsonld.link does the job, and JSONify looks very interesting.

Why is JSONify expecting real iris only? Some data have predicate that don't link to a real resource.

I'm definitely interested about the rdfjs discussion, although still a bit confused. I'll try to join you on Thursday.

**Pull request closed without merging**
